<?php

namespace Database\Seeders;


use App\Models\EntidadesModel;
use Illuminate\Database\Seeder;

class EntidadesSeed extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $datos = [
            array('nombre' => 'Secretaria Distrital de Gobierno'),
            array('nombre' => 'Departamento Administrativo de la Defensoría del Espacio Público -DADEP-'),
            array('nombre' => 'Instituto Distrital de la Participación y Acción Comunal -IDPA-'),
            array('nombre' => 'Secretaria General'),
            array('nombre' => 'Departamento Administrativo del Servicio Civil Distrital -DASCD-'),
            array('nombre' => 'Secretaría Distrital de Hacienda'),
            array('nombre' => 'Fondo de Prestaciones Económicas, Cesantías y Pensiones -FONCEP-'),
            array('nombre' => 'Unidad Administrativa Especial de Catastro Distrital -UAECD-'),
            array('nombre' => 'Lotería de Bogotá'),
            array('nombre' => 'Secretaría Distrital de Desarrollo Económico'),
            array('nombre' => 'Instituto para la Economía Social -IPES-'),
            array('nombre' => 'Instituto Distrital de Turismo -IDT-'),
            array('nombre' => 'Corporación para el Desarrollo y la Productividad Bogotá Región (Invest in Bogotá)'),
            array('nombre' => 'Secretaría Distrital de Planeación'),
            array('nombre' => 'Secretaría Distrital de Movilidad'),
            array('nombre' => 'Unidad Administrativa Especial de Rehabilitación y Mantenimiento Vial -UAERMV-'),
            array('nombre' => 'Instituto de Desarrollo Urbano -IDU-'),
            array('nombre' => 'Empresa de Transporte del Tercer Milenio -Transmilenio S.A.'),
            array('nombre' => 'Terminal de Transportes S.A.'),
            array('nombre' => 'Empresa Metro de Bogotá S.A.'),
            array('nombre' => 'Secretaria de Educación del Distrito'),
            array('nombre' => 'Instituto Distrital para la Investigación Educativa y el Desarrollo Pedagógico -IDEP-'),
            array('nombre' => 'Secretaría Distrital de Cultura, Recreación y Deporte'),
            array('nombre' => 'Instituto Distrital de Recreación y Deporte -IDRD-'),
            array('nombre' => 'Orquesta Filarmónica de Bogotá -OFB-'),
            array('nombre' => 'Fundación Gilberto Alzate Avendaño'),
            array('nombre' => 'Instituto Distrital de Patrimonio Cultural -IDPC-'),
            array('nombre' => 'Instituto Distrital de las Artes -IDARTES-'),
            array('nombre' => 'Universidad Distrital Francisco José de Caldas.'),
            array('nombre' => 'Canal Capital'),
            array('nombre' => 'Secretaria Distrital de Salud'),
            array('nombre' => 'Fondo Financiero Distrital de Salud -FFDS-'),
            array('nombre' => 'Subred Integrada de Servicios de Salud Sur E.S.E.'),
            array('nombre' => 'Subred Integrada de Servicios de Salud Sur Occidente E.S.E.'),
            array('nombre' => 'Subred Integrada de Servicios de Salud Norte E.S.E.'),
            array('nombre' => 'Subred Integrada de Servicios de Salud Centro Oriente E.S.E.'),
            array('nombre' => 'Capital Salud EPS-S S.A.S'),
            array('nombre' => 'Entidad Asesora de Gestión Administrativa y Técnica'),
            array('nombre' => 'Instituto Distrital de Ciencia, Biotecnología Innovación en Salud -IDCBIS-'),
            array('nombre' => 'Secretaria Distrital de Ambiente'),
            array('nombre' => 'Jardín Botánico José Celestino Mutis -JBB-'),
            array('nombre' => 'Instituto Distrital de Gestión de Riesgos y Cambio Climático -IDIGER (FONDIGER)-'),
            array('nombre' => 'Instituto Distrital de Protección y Bienestar Animal -IDPYBA-'),
            array('nombre' => 'Secretaria Distrital de Hábitat'),
            array('nombre' => 'Unidad Administrativa Especial de Servicios Públicos -UAESP-'),
            array('nombre' => 'Caja de Vivienda Popular -CVP-'),
            array('nombre' => 'Empresa de Renovación y Desarrollo Urbano de Bogotá D.C.'),
            array('nombre' => 'Empresa de Energía de Bogotá S.A. -EEB- -ESP-'),
            array('nombre' => 'Empresa de Acueducto Alcantarillado y Aseo de Bogotá -EAB- -ESP-'),
            array('nombre' => 'Empresa de Telecomunicaciones de Bogotá S.A. -ETB- -ESP-'),
            array('nombre' => 'Secretaria Distrital de la Mujer'),
            array('nombre' => 'Secretaria Distrital de Integración Social'),
            array('nombre' => 'Instituto Distrital para la Protección de la Niñez y la Juventud -IDIPRON-'),
            array('nombre' => 'Secretaría Distrital de Seguridad, Convivencia y Justicia'),
            array('nombre' => 'Unidad Administrativa Especial Cuerpo Oficial de Bomberos'),
            array('nombre' => 'Secretaria Jurídica Distrital'),
            array('nombre' => 'Contraloría De Bogotá', 'tipo' => 4),
            array('nombre' => 'Veeduría Distrital', 'tipo' => 4),
            array('nombre' => 'Concejo Distrital', 'tipo' => 4),
            array('nombre' => 'Procuraduría General De La Nación', 'tipo' => 4),
            array('nombre' => 'Secretaría Distrital De Gobierno', 'tipo' => 4),
            array('nombre' => 'Departamento De La Defensoría Del Espacio Público', 'tipo' => 4),
            array('nombre' => 'Instituto Distrital De La Participación Y Acción Comunal', 'tipo' => 4),
            array('nombre' => 'Secretaría General', 'tipo' => 4),
            array('nombre' => 'Departamento Administrativo Del Servicio Distrital', 'tipo' => 4),
            array('nombre' => 'Secretaría Juridica Distrital', 'tipo' => 4),
            array('nombre' => 'Fondo De Prestaciones Económicas, Cesantías Y Pensiones-Foncep', 'tipo' => 4),
            array('nombre' => 'Instituto Para La Economía Social - Ipes', 'tipo' => 4),
            array('nombre' => 'Secretaría Distrital De Hacienda', 'tipo' => 4),
            array('nombre' => 'Unidad Administrativa Especial De Catastro Distrital', 'tipo' => 4),
            array('nombre' => 'Lotería De Bogotá', 'tipo' => 4),
            array('nombre' => 'Secretaría Distrital De Desarrollo Económico', 'tipo' => 4),
            array('nombre' => 'Instituto Distrital De Turismo- Idt', 'tipo' => 4),
            array('nombre' => 'Secretaría Distrital De Movilidad', 'tipo' => 4),
            array('nombre' => 'Unidad Administrativa Especial De Rehabilitación Y Mantenimiento Vial', 'tipo' => 4),
            array('nombre' => 'Instituto De Desarrollo Urbano- Idu', 'tipo' => 4),
            array('nombre' => 'Empresa De Transporte Del Tercer Milenio - Transmilenio S.A.', 'tipo' => 4),
            array('nombre' => 'Empresa Metro De Bogotá', 'tipo' => 4),
            array('nombre' => 'Secretaría Distrital De Planeación', 'tipo' => 4),
            array('nombre' => 'Instituto Para La Investigación Educativa Y El Desarrollo Pedagógico', 'tipo' => 4),
            array('nombre' => 'Secretaría De Educación Distrital', 'tipo' => 4),
            array('nombre' => 'Universidad Distrital Francisco José De Caldas', 'tipo' => 4),
            array('nombre' => 'Instituto Distrital De Recreación Y Deporte - Idrd', 'tipo' => 4),
            array('nombre' => 'Instituto Distrital De Artes - Idartes', 'tipo' => 4),
            array('nombre' => 'Canal Capital', 'tipo' => 4),
            array('nombre' => 'Orquesta Filarmónica De Bogotá', 'tipo' => 4),
            array('nombre' => 'Instituto Distrital De Patrimonio Cultural', 'tipo' => 4),
            array('nombre' => 'Fundación Gilberto Alzate Avendaño', 'tipo' => 4),
            array('nombre' => 'Secretaría Distrital De Cultura Recreación Y Deporte', 'tipo' => 4),
            array('nombre' => 'Instituto Distrital De Gestión De Riesgos Y Cambio Climatico', 'tipo' => 4),
            array('nombre' => 'Secretría Distrital De Ambiente', 'tipo' => 4),
            array('nombre' => 'Jardín Botánico José Celestino Mutis', 'tipo' => 4),
            array('nombre' => 'Instituto Distrital De Protección Y Bienestar Animal', 'tipo' => 4),
            array('nombre' => 'Secretaría Distrital Del Habitat', 'tipo' => 4),
            array('nombre' => 'Unidad Administrativa Especial De Servicios Públicos', 'tipo' => 4),
            array('nombre' => 'Caja De Vivienda Popular', 'tipo' => 4),
            array('nombre' => 'Empresa De Renovación Y Desarrollo Urbano De Bogotá', 'tipo' => 4),
            array('nombre' => 'Empresa De Acuedcuto Alcantarillado Y Aseo De Bogotáempresa De Energía De Bogotá', 'tipo' => 4),
            array('nombre' => 'Empresa De Telecomunicaciones De Bogotá', 'tipo' => 4),
            array('nombre' => 'Secretaría Distrital De La Mujer', 'tipo' => 4),
            array('nombre' => 'Secretaría Dsitrital De Integración Social', 'tipo' => 4),
            array('nombre' => 'Instituto Para La Proteccion De La Niñez Y La Juventud - Idipron', 'tipo' => 4),
            array('nombre' => 'Secretría Distrital De Salud', 'tipo' => 4),
            array('nombre' => 'Fondo Financiero Dsitrital De Salud', 'tipo' => 4),
            array('nombre' => 'Subred Integrada De Servicios De Salud Del Sur', 'tipo' => 4),
            array('nombre' => 'Subred Integrada De Servicios De Salud Sur Occidente', 'tipo' => 4),
            array('nombre' => 'Subred Integrada De Servicios De Salud Norte', 'tipo' => 4),
            array('nombre' => 'Subred Integrada De Servicios De Salud Centro Oriente', 'tipo' => 4),
            array('nombre' => 'Capital Salud', 'tipo' => 4),
            array('nombre' => 'Entidad Asesora De Gestión Adminsitrativa Y Técnica', 'tipo' => 4),
            array('nombre' => 'Instituto Distrital De Ciencia Y Biotecnología, Inovacvión En Salud', 'tipo' => 4),
            array('nombre' => 'Secretaría Distrital De Seguridad, Convivencia Y Justicia', 'tipo' => 4),
            array('nombre' => 'Unidad Administrativa Especial Cuerpo Oficial De Bomberos', 'tipo' => 4),
            array('nombre' => 'Fondo De Desarrollo Local Usaquen', 'tipo' => 4),
            array('nombre' => 'Fondo De Desarrollo Local Chapinero', 'tipo' => 4),
            array('nombre' => 'Fondo De Desarrollo Local Santa Fe', 'tipo' => 4),
            array('nombre' => 'Fondo De Desarrollo Local San Cristobal', 'tipo' => 4),
            array('nombre' => 'Fondo De Desarrollo Local Usme', 'tipo' => 4),
            array('nombre' => 'Fondo De Desarrollo Local Tunjuelito', 'tipo' => 4),
            array('nombre' => 'Fondo De Desarrollo Local Bosa', 'tipo' => 4),
            array('nombre' => 'Fondo De Desarrollo Local Kennedy', 'tipo' => 4),
            array('nombre' => 'Fondo De Desarrollo Local Fontibon', 'tipo' => 4),
            array('nombre' => 'Fondo De Desarrollo Local Engativa', 'tipo' => 4),
            array('nombre' => 'Fondo De Desarrollo Local Suba', 'tipo' => 4),
            array('nombre' => 'Fondo De Desarrollo Local Barrios Unidos', 'tipo' => 4),
            array('nombre' => 'Fondo De Desarrollo Local Teusaquillo', 'tipo' => 4),
            array('nombre' => 'Fondo De Desarrollo Local Mártires', 'tipo' => 4),
            array('nombre' => 'Fondo De Desarrollo Local Antonio Nariño', 'tipo' => 4),
            array('nombre' => 'Fondo De Desarrollo Local Puente Aranda', 'tipo' => 4),
            array('nombre' => 'Fondo De Desarrollo Local Candelaria', 'tipo' => 4),
            array('nombre' => 'Fondo De Desarrollo Local Rafael Uribe', 'tipo' => 4),
            array('nombre' => 'Fondo De Desarrollo Local Ciudad Bolivar', 'tipo' => 4),
            array('nombre' => 'Fondo De Desarrollo Local Sumapaz', 'tipo' => 4),
            array('nombre' => 'Direcciones Locales De Educación', 'tipo' => 4),
            array('nombre' => 'Subdirecciones De Integracion Social', 'tipo' => 4),
            array('nombre' => 'Inspecciones De Policia Local Y Distrital', 'tipo' => 4),
            array('nombre' => 'Hogares Geriatricos Y Gerontologicos', 'tipo' => 4),
        ];
        for ($i=0; $i < count($datos); $i++) {
            EntidadesModel::create($datos[$i]);
        }
    }
}
